### ISSUE TITLE
Update conference and workshop list

### ISSUE THREAD

**Issue by jnnr** [energysystems/docs#14]
As I started listing conferences and summer schools for myself, I noticed that this repo is the better place to maintain it for the benefit of the whole group.

These items could be added. I have not been to either of these, so please comment if some of them are not interesting at all. You can help by adding items to this list or adding some description. 

I will open a PR soon once there is enough material here.

## Energy informatics
**In brief**: 

**What you can present**: 

**Publishing options**: 

**Next chance to participate**:

**Website**: [www.energy-informatics2023.org](https://www.energy-informatics2023.org/)

## Power system computation conference

**In brief**: 

**What you can present**: 

**Publishing options**: 

**Next chance to participate**:

**Website**: [https://pscc.epfl.ch/openconf.php](https://pscc.epfl.ch/openconf.php)

## SDEWES

**In brief**: 

**What you can present**: 

**Publishing options**: 

**Next chance to participate**:

**Website**: [https://www.dubrovnik2023.sdewes.org/](https://www.dubrovnik2023.sdewes.org/)

## ECEMP

**In brief**: 

**What you can present**: 

**Publishing options**: 

**Next chance to participate**:

**Website**: [https://www.ecemf.eu/ecemp/ecemp-2023/](https://www.ecemf.eu/ecemp/ecemp-2023/)

## DTU PES Summer school

**In brief**: 

**What you can present**: 

**Publishing options**: 

**Next chance to participate**:

**Website**: [https://energy-markets-school.dk/](https://energy-markets-school.dk/)

## ETH Summer school: Energy Technology, Policy and Politics

**In brief**: 

**What you can present**: 

**Publishing options**: 

**Next chance to participate**:

**Website**: [https://esc.ethz.ch/education/summer-school-2023.html](https://esc.ethz.ch/education/summer-school-2023.html)

**Comment by jnnr** [comment]
Another summer school in Trieste was mentioned in some of our team meetings.

**Comment by wwwuFei** [comment]
Thanks for putting these nice info together! Just one comment: I think ECEMP (previously as EMP-E or ECEMF) is already covered in our [doc](https://energysystems-docs.netlify.app/general/conferences.html#emp-e-energy-modelling-platform-for-europe). So we don't need to add it here anymore :)
